/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '10/10/20 2:01 PM' with Gradle 3.0
 *
 * @author Hp, @date 10/10/20 2:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
